name: Build BETAFPVG473

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout led-aux8
        uses: actions/checkout@v4
        with:
          submodules: recursive


      - name: Install ARM toolchain
        run: make arm_sdk_install
      - name: Clone Betaflight config
        run: make configs
      - run: mkdir -p obj/main/betaflight_STM32G474_BEFH
      - run: mkdir -p obj/betaflight_2026.6.2_STM32G474_BEFH
      - name: Build BETAFPVG473
        run: make CONFIG=BEFH/BETAFPVG473

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: BETAFPVG473-led-aux8
          path: obj/betaflight_2026.6.2_STM32G474_BEFH/*.hex
